# KEGG GSEA analysis using ranked limma t-statistics
# Input: ranked files generated by 02_differential_expression_limma_volcano.R
# Output: KEGG GSEA tables, bubble plots, and pathway gene-symbol files

cran_packages <- c(
  "dplyr", "tidyr", "readr", "ggplot2", "openxlsx",
  "svglite", "stringr", "forcats"
)

for (p in cran_packages) {
  if (!requireNamespace(p, quietly = TRUE)) {
    install.packages(p, dependencies = TRUE)
  }
  library(p, character.only = TRUE)
}

if (!requireNamespace("BiocManager", quietly = TRUE)) {
  install.packages("BiocManager")
}

bioc_packages <- c(
  "clusterProfiler", "org.Mm.eg.db", "AnnotationDbi", "enrichplot"
)

for (p in bioc_packages) {
  if (!requireNamespace(p, quietly = TRUE)) {
    BiocManager::install(p)
  }
  library(p, character.only = TRUE)
}

input_rank_dir <- "outputs/GSEA"

output_gsea_dir <- "outputs/GSEA/KEGG"
plot_dir <- file.path(output_gsea_dir, "bubble_plots")
excel_dir <- file.path(output_gsea_dir, "excel_results")
gene_dir <- file.path(output_gsea_dir, "pathway_gene_lists")

dir.create(output_gsea_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(plot_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(excel_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(gene_dir, recursive = TRUE, showWarnings = FALSE)

ranked_files <- list(
  "15KO_MCA_vs_WT_MCA" = file.path(input_rank_dir, "GSEA_ranked_15KO_MCA_vs_WT_MCA.csv"),
  "RAKO_MCA_vs_WT_MCA" = file.path(input_rank_dir, "GSEA_ranked_RAKO_MCA_vs_WT_MCA.csv"),
  "RAKO_MCA_vs_15KO_MCA" = file.path(input_rank_dir, "GSEA_ranked_RAKO_MCA_vs_15KO_MCA.csv")
)

missing_files <- ranked_files[!file.exists(unlist(ranked_files))]

if (length(missing_files) > 0) {
  stop(
    "Missing ranked input files: ",
    paste(unlist(missing_files), collapse = ", "),
    "\nRun scripts/02_differential_expression_limma_volcano.R first."
  )
}

prepare_ranked_vector <- function(file_path) {

  ranked_df <- readr::read_csv(file_path, show_col_types = FALSE)

  if (!all(c("GSEA_gene", "t") %in% colnames(ranked_df))) {
    stop("Input ranked file must contain columns named GSEA_gene and t.")
  }

  ranked_df <- ranked_df %>%
    dplyr::filter(!is.na(GSEA_gene), !is.na(t)) %>%
    dplyr::mutate(
      GSEA_gene = as.character(GSEA_gene),
      t = as.numeric(t)
    ) %>%
    dplyr::filter(!is.na(t)) %>%
    dplyr::group_by(GSEA_gene) %>%
    dplyr::slice_max(order_by = abs(t), n = 1, with_ties = FALSE) %>%
    dplyr::ungroup()

  gene_map <- AnnotationDbi::select(
    org.Mm.eg.db,
    keys = ranked_df$GSEA_gene,
    keytype = "SYMBOL",
    columns = c("ENTREZID", "SYMBOL")
  )

  ranked_mapped <- ranked_df %>%
    dplyr::left_join(gene_map, by = c("GSEA_gene" = "SYMBOL")) %>%
    dplyr::filter(!is.na(ENTREZID)) %>%
    dplyr::group_by(ENTREZID) %>%
    dplyr::slice_max(order_by = abs(t), n = 1, with_ties = FALSE) %>%
    dplyr::ungroup() %>%
    dplyr::arrange(desc(t))

  gene_list <- ranked_mapped$t
  names(gene_list) <- ranked_mapped$ENTREZID
  gene_list <- sort(gene_list, decreasing = TRUE)

  list(
    ranked_original = ranked_df,
    ranked_mapped = ranked_mapped,
    gene_list = gene_list
  )
}

convert_core_enrichment_to_symbols <- function(core_enrichment_string) {

  entrez_ids <- unlist(strsplit(core_enrichment_string, "/"))
  entrez_ids <- unique(entrez_ids[!is.na(entrez_ids) & entrez_ids != ""])

  if (length(entrez_ids) == 0) {
    return(NA_character_)
  }

  mapped <- AnnotationDbi::select(
    org.Mm.eg.db,
    keys = entrez_ids,
    keytype = "ENTREZID",
    columns = c("SYMBOL")
  )

  symbols <- unique(mapped$SYMBOL[!is.na(mapped$SYMBOL)])

  if (length(symbols) == 0) {
    return(NA_character_)
  }

  paste(symbols, collapse = ";")
}

run_kegg_gsea <- function(gene_list) {

  gsea_res <- clusterProfiler::gseKEGG(
    geneList = gene_list,
    organism = "mmu",
    keyType = "ncbi-geneid",
    minGSSize = 10,
    maxGSSize = 500,
    pvalueCutoff = 1,
    pAdjustMethod = "BH",
    eps = 0,
    verbose = FALSE
  )

  gsea_df <- as.data.frame(gsea_res)

  if (nrow(gsea_df) == 0) {
    return(gsea_df)
  }

  gsea_df <- gsea_df %>%
    dplyr::mutate(
      Direction = dplyr::case_when(
        NES > 0 ~ "Up",
        NES < 0 ~ "Down",
        TRUE ~ "Neutral"
      ),
      Significance = dplyr::case_when(
        p.adjust < 0.05 ~ "*",
        p.adjust < 0.10 ~ "#",
        TRUE ~ ""
      ),
      minus_log10_FDR = -log10(p.adjust),
      Core_enrichment_Entrez = core_enrichment,
      Core_enrichment_Symbols = sapply(core_enrichment, convert_core_enrichment_to_symbols),
      Pathway_Label = Description
    )

  gsea_df
}

select_top_pathways <- function(gsea_df, n_each = 15) {

  top_up <- gsea_df %>%
    dplyr::filter(NES > 0) %>%
    dplyr::arrange(p.adjust, dplyr::desc(NES)) %>%
    dplyr::slice_head(n = n_each)

  top_down <- gsea_df %>%
    dplyr::filter(NES < 0) %>%
    dplyr::arrange(p.adjust, NES) %>%
    dplyr::slice_head(n = n_each)

  dplyr::bind_rows(top_up, top_down) %>%
    dplyr::arrange(NES) %>%
    dplyr::mutate(
      Pathway_Label = factor(Pathway_Label, levels = unique(Pathway_Label))
    )
}

save_plot_all <- function(plot, filename, width = 10, height = 9, dpi = 600) {

  ggplot2::ggsave(
    file.path(plot_dir, paste0(filename, ".jpg")),
    plot,
    width = width,
    height = height,
    dpi = dpi,
    bg = "white"
  )

  ggplot2::ggsave(
    file.path(plot_dir, paste0(filename, ".pdf")),
    plot,
    width = width,
    height = height,
    device = cairo_pdf,
    bg = "white"
  )

  ggplot2::ggsave(
    file.path(plot_dir, paste0(filename, ".svg")),
    plot,
    width = width,
    height = height,
    device = svglite::svglite,
    bg = "white"
  )
}

make_bubble_plot <- function(plot_df, comparison_name) {

  x_range <- range(plot_df$NES, na.rm = TRUE)
  x_offset <- diff(x_range) * 0.035

  plot_df <- plot_df %>%
    dplyr::mutate(
      Symbol_x = ifelse(NES >= 0, NES + x_offset, NES - x_offset),
      Symbol_hjust = ifelse(NES >= 0, 0, 1)
    )

  ggplot(plot_df, aes(x = NES, y = Pathway_Label)) +
    geom_vline(xintercept = 0, linetype = "dashed", linewidth = 0.4) +
    geom_point(
      aes(size = setSize, fill = Direction),
      shape = 21,
      color = "black",
      stroke = 0.35,
      alpha = 0.92
    ) +
    geom_text(
      aes(x = Symbol_x, label = Significance, hjust = Symbol_hjust),
      size = 5,
      fontface = "bold",
      color = "black"
    ) +
    scale_fill_manual(
      values = c(
        "Up" = "green3",
        "Down" = "#4B2E1A",
        "Neutral" = "grey70"
      )
    ) +
    scale_size_continuous(range = c(3.5, 11)) +
    scale_x_continuous(expand = expansion(mult = c(0.10, 0.12))) +
    labs(
      title = paste0("KEGG GSEA: ", comparison_name),
      subtitle = "* FDR < 0.05; # FDR < 0.10",
      x = "Normalized Enrichment Score (NES)",
      y = NULL,
      size = "Gene set size",
      fill = "Direction"
    ) +
    theme_classic(base_size = 13) +
    theme(
      axis.text = element_text(color = "black"),
      axis.text.y = element_text(size = 10),
      axis.title.x = element_text(face = "bold", color = "black"),
      plot.title = element_text(face = "bold", hjust = 0.5),
      plot.subtitle = element_text(hjust = 0.5),
      legend.title = element_text(face = "bold"),
      panel.border = element_rect(color = "black", fill = NA, linewidth = 0.5)
    )
}

all_gsea_results <- list()
all_plot_data <- list()
all_pathway_gene_long <- list()

for (comparison_name in names(ranked_files)) {

  message("Running KEGG GSEA for: ", comparison_name)

  prepared <- prepare_ranked_vector(ranked_files[[comparison_name]])
  gsea_df <- run_kegg_gsea(prepared$gene_list)

  if (nrow(gsea_df) == 0) {
    warning("No KEGG GSEA results for ", comparison_name)
    next
  }

  gsea_df$Comparison <- comparison_name

  plot_df <- select_top_pathways(gsea_df, n_each = 15)
  plot_df$Comparison <- comparison_name

  p <- make_bubble_plot(plot_df, comparison_name)
  save_plot_all(p, paste0("KEGG_GSEA_bubble_", comparison_name), width = 11, height = 9)

  pathway_gene_long <- gsea_df %>%
    dplyr::select(
      Comparison,
      ID,
      Description,
      NES,
      pvalue,
      p.adjust,
      Direction,
      Significance,
      Core_enrichment_Entrez,
      Core_enrichment_Symbols
    ) %>%
    tidyr::separate_rows(Core_enrichment_Symbols, sep = ";") %>%
    dplyr::rename(Gene_Symbol = Core_enrichment_Symbols) %>%
    dplyr::filter(!is.na(Gene_Symbol), Gene_Symbol != "") %>%
    dplyr::arrange(Comparison, Description, Gene_Symbol)

  write.csv(
    pathway_gene_long,
    file.path(gene_dir, paste0("Pathway_gene_symbols_", comparison_name, ".csv")),
    row.names = FALSE
  )

  all_gsea_results[[comparison_name]] <- gsea_df
  all_plot_data[[comparison_name]] <- plot_df
  all_pathway_gene_long[[comparison_name]] <- pathway_gene_long
}

combined_gsea <- dplyr::bind_rows(all_gsea_results)
combined_plot_df <- dplyr::bind_rows(all_plot_data)
combined_pathway_genes <- dplyr::bind_rows(all_pathway_gene_long)

panel_df <- combined_plot_df %>%
  dplyr::mutate(
    Comparison = factor(
      Comparison,
      levels = c(
        "15KO_MCA_vs_WT_MCA",
        "RAKO_MCA_vs_WT_MCA",
        "RAKO_MCA_vs_15KO_MCA"
      )
    )
  )

x_range_panel <- range(panel_df$NES, na.rm = TRUE)
x_offset_panel <- diff(x_range_panel) * 0.035

panel_df <- panel_df %>%
  dplyr::mutate(
    Symbol_x = ifelse(NES >= 0, NES + x_offset_panel, NES - x_offset_panel),
    Symbol_hjust = ifelse(NES >= 0, 0, 1)
  )

p_panel <- ggplot(panel_df, aes(x = NES, y = Pathway_Label)) +
  geom_vline(xintercept = 0, linetype = "dashed", linewidth = 0.35) +
  geom_point(
    aes(size = setSize, fill = Direction),
    shape = 21,
    color = "black",
    stroke = 0.3,
    alpha = 0.92
  ) +
  geom_text(
    aes(x = Symbol_x, label = Significance, hjust = Symbol_hjust),
    size = 4.2,
    fontface = "bold",
    color = "black"
  ) +
  scale_fill_manual(
    values = c(
      "Up" = "green3",
      "Down" = "#4B2E1A",
      "Neutral" = "grey70"
    )
  ) +
  scale_size_continuous(range = c(2.8, 9)) +
  scale_x_continuous(expand = expansion(mult = c(0.10, 0.13))) +
  facet_wrap(~ Comparison, scales = "free_y", ncol = 1) +
  labs(
    title = "KEGG GSEA Bubble Plot Panel",
    subtitle = "Top 15 upregulated and top 15 downregulated KEGG pathways per comparison; * FDR < 0.05; # FDR < 0.10",
    x = "Normalized Enrichment Score (NES)",
    y = NULL,
    size = "Gene set size",
    fill = "Direction"
  ) +
  theme_classic(base_size = 13) +
  theme(
    axis.text = element_text(color = "black"),
    axis.text.y = element_text(size = 8.5),
    axis.title.x = element_text(face = "bold", color = "black"),
    plot.title = element_text(face = "bold", hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5),
    strip.background = element_rect(fill = "grey90", color = "black"),
    strip.text = element_text(face = "bold"),
    legend.title = element_text(face = "bold"),
    panel.border = element_rect(color = "black", fill = NA, linewidth = 0.5)
  )

save_plot_all(
  p_panel,
  "KEGG_GSEA_bubble_PANEL_all_comparisons",
  width = 12,
  height = 18
)

wb <- openxlsx::createWorkbook()

openxlsx::addWorksheet(wb, "Analysis_Description")
analysis_description <- data.frame(
  Step = c(
    "Input files",
    "Gene ranking",
    "Gene ID conversion",
    "GSEA method",
    "Organism",
    "Direction",
    "Significance symbols",
    "Bubble plot symbol placement",
    "Pathway gene symbols",
    "Heatmap use"
  ),
  Description = c(
    "Ranked CSV files generated from limma differential expression analysis were used as input.",
    "The moderated t-statistic was used as the ranking metric.",
    "Mouse gene symbols were converted to Entrez IDs using org.Mm.eg.db for KEGG GSEA.",
    "KEGG GSEA was performed using clusterProfiler::gseKEGG with Benjamini-Hochberg FDR correction.",
    "The KEGG organism code was mmu for Mus musculus.",
    "Positive NES indicates enrichment in the numerator condition. Negative NES indicates enrichment in the denominator condition.",
    "An asterisk (*) indicates FDR < 0.05. A hash symbol (#) indicates FDR < 0.10.",
    "Significance symbols were placed beside each bubble rather than appended to pathway names.",
    "The core enrichment gene IDs were converted back to mouse gene symbols and exported for every pathway.",
    "The pathway gene-symbol outputs can be used to select genes for pathway-specific heatmaps."
  )
)

openxlsx::writeData(wb, "Analysis_Description", analysis_description)

openxlsx::addWorksheet(wb, "Combined_GSEA_All")
openxlsx::writeData(wb, "Combined_GSEA_All", combined_gsea)

openxlsx::addWorksheet(wb, "Combined_Top15_Up_Down")
openxlsx::writeData(wb, "Combined_Top15_Up_Down", combined_plot_df)

openxlsx::addWorksheet(wb, "Pathway_Gene_Symbols")
openxlsx::writeData(wb, "Pathway_Gene_Symbols", combined_pathway_genes)

for (comparison_name in names(all_gsea_results)) {

  safe_name <- stringr::str_replace_all(comparison_name, "[^A-Za-z0-9_]", "_")

  openxlsx::addWorksheet(wb, paste0(safe_name, "_All"))
  openxlsx::writeData(wb, paste0(safe_name, "_All"), all_gsea_results[[comparison_name]])

  openxlsx::addWorksheet(wb, paste0(safe_name, "_Top15"))
  openxlsx::writeData(wb, paste0(safe_name, "_Top15"), all_plot_data[[comparison_name]])

  openxlsx::addWorksheet(wb, paste0(safe_name, "_Genes"))
  openxlsx::writeData(wb, paste0(safe_name, "_Genes"), all_pathway_gene_long[[comparison_name]])
}

header_style <- openxlsx::createStyle(
  textDecoration = "bold",
  fgFill = "#D9EAD3",
  border = "Bottom"
)

for (s in names(wb)) {
  openxlsx::addStyle(
    wb,
    s,
    header_style,
    rows = 1,
    cols = 1:100,
    gridExpand = TRUE
  )
  openxlsx::freezePane(wb, s, firstRow = TRUE)
  openxlsx::setColWidths(wb, s, cols = 1:100, widths = "auto")
}

excel_out <- file.path(excel_dir, "KEGG_GSEA_Report_with_Pathway_Gene_Symbols.xlsx")
openxlsx::saveWorkbook(wb, excel_out, overwrite = TRUE)

write.csv(
  combined_gsea,
  file.path(output_gsea_dir, "Combined_KEGG_GSEA_all_results.csv"),
  row.names = FALSE
)

write.csv(
  combined_plot_df,
  file.path(output_gsea_dir, "Combined_KEGG_GSEA_top15_up_down_for_plots.csv"),
  row.names = FALSE
)

write.csv(
  combined_pathway_genes,
  file.path(output_gsea_dir, "Combined_KEGG_GSEA_pathway_gene_symbols_long_format.csv"),
  row.names = FALSE
)

message("KEGG GSEA analysis completed successfully.")
message("Excel report saved to: ", excel_out)
message("Pathway gene-symbol files saved to: ", gene_dir)
message("Bubble plots saved to: ", plot_dir)
